EntityFramworkProject/Models/ErrorViewModel.cs
using System;

namespace EntityFramworkProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EntityFramworkProject/Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using BussinessLayer;

namespace EntityFramworkProject.Controllers
{
    public class CrudController : Controller
    {
        
        private readonly IProductComponent _productComponent;
        public CrudController(IProductComponent productComponent)
        {
            _productComponent = productComponent;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Details(int id)
        {
            return View(_productComponent.GetSingleProduct(id));
        }
        public ActionResult DisplayProducts()
        {
            return View(_productComponent.GetProducts());
        }
        // GET:Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StudentEntities.Entities.Products model)
        {
            try
            {
                var added = _productComponent.AddProduct(model);
                return RedirectToAction(nameof(DisplayProducts), _productComponent.GetProducts());
            }
            catch(Exception e)
            {
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            return View(_productComponent.GetSingleProduct(id));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, StudentEntities.Entities.Products model)
        {
            try
            {
                var edited = _productComponent.EditProdcut(id, model);
                return RedirectToAction(nameof(DisplayProducts),_productComponent.GetProducts());
            }
            catch
            {
                return View();
            }
        }

        // GET: Delete
        public ActionResult Delete(int id)
        {
            return View(_productComponent.GetSingleProduct(id));
        }
        // POST: Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, StudentEntities.Entities.Products model)
        {
            try
            {
                _productComponent.DeleteProduct(id);
                return RedirectToAction(nameof(DisplayProducts), _productComponent.GetProducts());
            }
            catch
            {
                return View();
            }
        }
    }
}

EntityFramworkProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EntityFramworkProject.Models;
using BussinessLayer;

namespace EntityFramworkProject.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EntityFramworkProject/Views/Crud/Create.cshtml
@model StudentEntities.Entities.Products

@{
    ViewData["Title"] = "Create";
}
<div class="container" >
<h1>Add Product</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDiscription" class="control-label"></label>
                <input asp-for="ProductDiscription" class="form-control" />
                <span asp-validation-for="ProductDiscription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductColor" class="control-label"></label>
                <input asp-for="ProductColor" class="form-control" />
                <span asp-validation-for="ProductColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoOfProducts" class="control-label"></label>
                <input asp-for="NoOfProducts" class="form-control" />
                <span asp-validation-for="NoOfProducts" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catagory" class="control-label"></label>
                <input asp-for="Catagory" class="form-control" />
                <span asp-validation-for="Catagory" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ShippingAllowed" /> @Html.DisplayNameFor(model => model.ShippingAllowed)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ExpiryDate" class="control-label"></label>
                <input asp-for="ExpiryDate" class="form-control" />
                <span asp-validation-for="ExpiryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="DisplayProducts">Back to List</a>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EntityFramworkProject/Views/Crud/Delete.cshtml
@model StudentEntities.Entities.Products

@{
    ViewData["Title"] = "Delete";
}
<div class="container">
<h1>Delete @Model.ProductName</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDiscription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductDiscription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductColor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductColor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoOfProducts)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoOfProducts)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Catagory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Catagory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShippingAllowed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShippingAllowed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="DisplayProducts">Back to List</a>
    </form>
</div>
 </div>

EntityFramworkProject/Views/Crud/Details.cshtml
@model StudentEntities.Entities.Products

@{
    ViewData["Title"] = "Details";
}
<div class="container">
<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDiscription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductDiscription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductColor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductColor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoOfProducts)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoOfProducts)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Catagory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Catagory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShippingAllowed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShippingAllowed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductId }) |
    <a asp-action="DisplayProducts">Back to List</a>
</div>
</div>

EntityFramworkProject/Views/Crud/DisplayProducts.cshtml
@model List<StudentEntities.Entities.Products>

@{
    ViewData["Title"] = "DisplayProducts";
}
    <div class="container">
        <h1>Products Details</h1>

        <p>
            <a asp-action="Create">Create New</a>
        </p>
        </div>
<table class="table table-bordered table-responsive table-hover" style="">
    <thead>
        <tr>
            
            <th>
                ProductName
            </th>
            <th>
                ProductDiscription
            </th>
            <th>
                ProductColor
            </th>
            <th>
                ProductPrice
            </th>
            <th>
                NoOfProducts
            </th>
            <th>
                Product Catagory
            </th>
            <th>
                ShippingAllowed
            </th>
            <th>
                ExpiryDate
            </th>
            <th>
                Edit
            </th>
            <th>
                Details
            </th>
            <th>
                Delete
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (StudentEntities.Entities.Products item in Model) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDiscription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductColor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoOfProducts)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Catagory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShippingAllowed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpiryDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ProductId }) 
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.ProductId })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id=item.ProductId })
            </td>

        </tr>
}
    </tbody>
</table>

EntityFramworkProject/Views/Crud/Edit.cshtml
@model StudentEntities.Entities.Products

@{
    ViewData["Title"] = "Edit";
}
<div class="container">
<h1>Edit</h1>

<h4>@Model.ProductName</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDiscription" class="control-label"></label>
                <input asp-for="ProductDiscription" class="form-control" />
                <span asp-validation-for="ProductDiscription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductColor" class="control-label"></label>
                <input asp-for="ProductColor" class="form-control" />
                <span asp-validation-for="ProductColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoOfProducts" class="control-label"></label>
                <input asp-for="NoOfProducts" class="form-control" />
                <span asp-validation-for="NoOfProducts" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Catagory" class="control-label"></label>
                <input asp-for="Catagory" class="form-control" />
                <span asp-validation-for="Catagory" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ShippingAllowed" /> @Html.DisplayNameFor(model => model.ShippingAllowed)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ExpiryDate" class="control-label"></label>
                <input asp-for="ExpiryDate" class="form-control" />
                <span asp-validation-for="ExpiryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="DisplayProducts">Back to List</a>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EntityFramworkProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EntityFramworkProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EntityFramworkProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EntityFramworkProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Crud" asp-action="DisplayProducts">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EntityFramworkProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>